name: Mac

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B mac_gcc -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build mac_gcc --parallel