name: Mac

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest LLVM
        run: brew install llvm
      - name: Configure
        run: cmake -B mac_build -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: LDFLAGS="-L$HOMEBREW_PREFIX/opt/llvm/lib/c++ -Wl,-rpath,$HOMEBREW_PREFIX/opt/llvm/lib/c++" cmake --build mac_build --parallel