name: Mac

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B mac_clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build mac_clang --parallel