name: Linux (clang)

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux-clang:
    name: Linux (clang)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libgl1-mesa-dev libglew-dev
      - name: Configure
        run: cmake -B linux_clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build linux_clang --parallel