name: Mac

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clang17
        run: brew install llvm@17
      - name: Configure
        run: cmake -B mac_build -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@17)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm@17)/bin/clang -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build mac_build --parallel